shared:
  # Task : sync and merge with rsync 2 rep. Used to merge stack and config
  - &merge-stack-and-config
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: cycloid/cycloid-toolkit
        tag: latest
    run:
      path: sh
      args:
        - '-ec'
        - |
          /usr/bin/merge-stack-and-config
          mkdir merged-stack/.kube
          echo "$KUBECONFIG" > merged-stack/.kube/config
    outputs:
    - name: merged-stack
      path: "merged-stack"

groups:
- name: overview
  jobs:
  - terraform-plan
  - terraform-apply
- name: destroy
  jobs:
  - terraform-destroy

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

resources:
- name: tfstate
  type: terraform
  source:
    backend_type: s3
    backend_config:
      bucket: ((terraform_storage_bucket_name))
      key: ((terraform_storage_bucket_path))
      region: ((s3_region))
      access_key: ((s3_access_key))
      secret_key: ((s3_secret_key))
    vars:
      customer: ((customer))
      env: ((env))
      project: ((project))
      sonarqube_admin_password: ((sonarqube_admin_password))
      postgresql_password: ((postgresql_password))
      sonarqube_image_tag: ((sonarqube_image_tag))
      sonarqube_domain: ((sonarqube_domain))
      kubernetes_namespace: ((kubernetes_namespace))
      ssl_secretname: ((ssl_secretname))
      plugins_install: ((plugins_install))
      plugins_lib: ((plugins_lib))

- name: git_stack-terraform
  type: git
  source:
    #uri: https://github.com/cycloid-community-catalog/stack-sonarqube
    uri: 'git@github.com:cycloid-community-catalog/stack-sonarqube.git'
    private_key: ((config_git_private_key))
    branch: master
    paths:
    - terraform/*

- name: git_config-terraform
  type: git
  source:
    uri: ((config_git_repository))
    branch: ((config_git_branch))
    private_key: ((config_git_private_key))
    paths:
    - ((project))/terraform/*

jobs:
  - name: terraform-plan
    build_logs_to_retain: 10
    plan:
      - do:
        - get: git_stack-terraform
          trigger: true
        - get: git_config-terraform
          trigger: true

        - task: merge-stack-and-config
          config:
            <<: *merge-stack-and-config
            inputs:
            - name: git_config-terraform
              path: "config"
            - name: git_stack-terraform
              path: "stack"
          params:
            KUBECONFIG: ((kubeconfig))
            CONFIG_PATH: ((project))/terraform/((env))
            STACK_PATH: terraform

        - put: tfstate
          params:
            plan_only: true
            env_name: ((project))-((env))
            terraform_source: merged-stack/

  - name: terraform-apply
    build_logs_to_retain: 10
    plan:
      - do:
        # Trigger false because of manual approval
        - get: git_stack-terraform
          trigger: false
          passed:
            - terraform-plan
        - get: git_config-terraform
          trigger: false

        - task: merge-stack-and-config
          config:
            <<: *merge-stack-and-config
            inputs:
            - name: git_config-terraform
              path: "config"
            - name: git_stack-terraform
              path: "stack"
          params:
            KUBECONFIG: ((kubeconfig))
            CONFIG_PATH: ((project))/terraform/((env))
            STACK_PATH: terraform

        - put: tfstate
          params:
            run_plan: true
            env_name: ((project))-((env))
            terraform_source: merged-stack/

  - name: terraform-destroy
    build_logs_to_retain: 10
    plan:
      - do:
        # Trigger false because of manual approval
        - get: git_stack-terraform
          trigger: false
        - get: git_config-terraform
          trigger: false
        - get: tfstate
          trigger: false

        - task: merge-stack-and-config
          config:
            <<: *merge-stack-and-config
            inputs:
            - name: git_config-terraform
              path: "config"
            - name: git_stack-terraform
              path: "stack"
          params:
            KUBECONFIG: ((kubeconfig))
            CONFIG_PATH: ((project))/terraform/((env))
            STACK_PATH: terraform

        - put: tfstate
          params:
            env_name: ((project))-((env))
            action: destroy
            terraform_source: merged-stack/
          get_params:
            action: destroy